name: CI Build

on: 
  push:
    paths-ignore:
    - '**/*.md'
    - '**/*.gitignore'
    - '**/*.gitattributes'
  pull_request:
    branches: [ master ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:

  build-windows:
    runs-on: windows-2022
    name: Windows Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-prerelease: true
        
      - name: Install MAUI Workloads
        run: |
          dotnet workload install maui

      - name: Restore Dependencies
        run: dotnet restore src/Blazedis.App/Blazedis.App.csproj

      - name: Build MAUI Windows
        run: msbuild src/Blazedis.App/Blazedis.App.csproj -r -p:Configuration=Release -p:RestorePackages=false -p:TargetFramework=net6.0-windows10.0.19041 /p:GenerateAppxPackageOnBuild=true

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: windows-ci-build
          path: src/Blazedis.App/bin/Release/net6.0-windows*/**/Blazedis.App*.msix

  build-android:
    runs-on: windows-2022
    name: Android Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          include-prerelease: true
          
      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '11'

      - name: Install MAUI Workloads
        run: |
          dotnet workload install android
          dotnet workload install maui

      - name: Restore Dependencies
        run: dotnet restore src/Blazedis.App/Blazedis.App.csproj

      - name: Build MAUI Android
        run: dotnet build src/Blazedis.App/Blazedis.App.csproj -c Release -f net6.0-android --no-restore

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: android-ci-build
          path: src/Blazedis.App/bin/Release/net6.0-android/*Signed.a*

  build-ios:
    runs-on: macos-11
    name: iOS Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - name: Install MAUI Workloads
        run: |
          dotnet workload install ios
          dotnet workload install maui

      - name: Restore Dependencies
        run: dotnet restore src/Blazedis.App/Blazedis.App.csproj

      - name: Build MAUI iOS
        run: dotnet build src/Blazedis.App/Blazedis.App.csproj -c Release -f net6.0-ios --no-restore

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: ios-ci-build
          path: src/Blazedis.App/bin/Release/net6.0-ios/**/*.app/
